
name: Acceptance test Test-PyPi

on:
  # workflow_run:
  #   workflows: ["Publish TestPyPi package"]
  #   types:
  #     - completed
  workflow_dispatch:
    inputs:
      target:
        required: true
    
    
permissions:
  contents: read

jobs:
  acceptance:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Test Package Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
        
    - name: Install dependencies
      run: |
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple robotframework-jsonvalidator
        pip install robotframework
        
    - name: Test with robot
      run: |
        robot test/atest.robot
