
name: Acceptance test Test-PyPi

on:
  # workflow_run:
  #   workflows: ["Publish TestPyPi package"]
  #   types:
  #     - completed
  workflow_dispatch:
    inputs:
      target:
        required: false
    
    
permissions:
  contents: read

jobs:
  acceptance:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Test Package Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"

    - name: create and activate venv
      run: |
        python -m venv venv
        source venv/bin/activate
        which python

        
    # - name: list files
    #   run: ls -la
        
    - name: Install dependencies
      run: |
        pip install robotframework
        pip install tabulate
        pip install jsonschema
        pip install --index-url https://test.pypi.org/simple/ robotframework-jsonvalidator
        python -c "import JsonValidator, inspect; print('JsonValidator loaded from:', getattr(JsonValidator, '__file__', '<no __file__>'))"
        python -m pip show -f robotframework-jsonvalidator
        python -m pip show -f JsonValidator || true
        python -m pip list | grep -i json || true
        ``

    - name: Validate Keywords exist
      run: python -m robot.libdoc JsonValidator list
        
    - name: Test with robot
      run: |
        python -m robot test/atest.robot
