# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Acceptance

on:
  workflow_run:
    workflows: ["Publish TestPyPi package"]
    types:
      - completed
    
    
permissions:
  contents: read

jobs:
  acceptance:
    name: Test Package Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
        
    - name: Install dependencies
      run: |
        pip install -i https://test.pypi.org/simple/ robotframework-jsonvalidator
        pip install robotframework
        
    - name: Test with pytest
      run: |
        robot test/atest.robot
