name: Build Package

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    env:
      dist_artifacts_name: dist
      dist_artifacts_dir: dist
      lock_file_artifact: uv.lock

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v7.6.0
        with:
          version: '0.11.1'

      - name: Install UV Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --group release --no-dev

      - name: Build | Next Version
        id: version
        env:
          GH_TOKEN: 'none'
        run: uv run semantic-release -v version --no-changelog --no-commit --no-tag

      - name: Upload | Distribution Artifact
        if: ${{ steps.version.outputs.release == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.dist_artifacts_name }}
          path: ${{ format( '{0}/**', env.dist_artifacts_dir) }}
          if-no-files-found: error
          retention-days: 2
