name: Tests and Build

on: push

jobs:
  comp_test:
    name: Exeute Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
            python-version:
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"
              - "3.14"
            rf_version:
              - "rf70"
              - "rf71"
              - "rf72"
              - "rf73"
              - "rf74"
    env:
         UV_PROJECT_ENVIRONMENT: .venv-${{ matrix.python-version }}-${{ matrix.rf_version }}
         
    steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        - name: Setup UV
          uses: astral-sh/setup-uv@v7.6.0
          with:
            version: 0.11.2
            python-version: ${{ matrix.python-version}}

        - name: install project
          run: uv sync --extra ${{ matrix.rf_version}} --no-dev

        - name: run Test
          run: uv run --no-sync robot test/atest.robot

  build:
    needs: comp_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv and python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | #shell
          sr() {
            uvx --from="python-semantic-release@9.21.1" semantic-release "$@"
          }

          sr version
          sr publish
