name: Publish TestPyPi package

on:
  # Manual Dispatch of release
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write   # nodig voor trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest

    # Dynamisch environment kiezen
    environment: 'testpypi'

    steps:
      - name: Checkout exact release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build package
        run: uv build

      - name: Publish | TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

