name: Test package

on: push

jobs:
    test:
       name: Exeute Tests
       runs-on: ubuntu-latest
       strategy:
        matrix:
            python-version:
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"
              - "3.14"
            rf_group:
              - "rf70"
              - "rf71"
              - "rf72"
              - "rf73"
              - "rf74"
       steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        - name: Setup UV
          uses: astral-sh/setup-uv@v7.6.0
          with:
            version: 0.11.2
            python-version: ${{ matrix.python-version}}

        - name: install project
          run: uv sync --only-group dev --only-group ${{ matrix.rf_group}}

        - name: run Test
          run: uv run robot test/atest.robot
