name: Test package

on: push

jobs:
    test:
       name: Exeute Tests
       runs-on: ubuntu-latest
       strategy:
        fail-fast: false
        max-parallel: 3
        matrix:
            python-version:
              - "3.10"
              - "3.11"
              - "3.12"
              - "3.13"
              - "3.14"
            rf_version:
              - "rf70"
         
       steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        - name: Setup UV
          uses: astral-sh/setup-uv@v7.6.0
          with:
            version: 0.11.2
            python-version: ${{ matrix.python-version}}

        - name: install project
          run: uv sync --extra ${{ matrix.rf_version}}

        - name: run Test
          run: uv run robot test/atest.robot
